### ISSUE TITLE
initial score is larger than score for the whole training process

### ISSUE THREAD

**Issue by deepmed2024** [Algolzw/SPAC-Deformable-Registration#12]
Dear author:
 Thanks for your sharing the code!. I try to replicate your performance using Lits.json as training set. However, it is tough to make score larger than initial score. I do not know what problem it is.  The training process can be seen in the Figure. Meanwhile, I also do some parameter adjustment. For example, decrease reward and alpha. But it still not work.  Could you give me some advice about this problem. Thanks for the help and looking forward to receiving your response.

![image](https://github.com/user-attachments/assets/b60e2eae-9241-4774-8aca-e7cfb929079a)

**Comment by pds001** [comment]
Hello, I found an error in the operation process, hope to get your help, good luck!
Number of data in combine-train is 2302
Number of data in lpba-val is 39
Traceback (most recent call last):
File "E:\SPAC-Deformable-Registration-main\code\main.py", line 63, in <module>
env = Env(generator, stn, seg_stn, cfg.USE_SEG, device)
File "E:\SPAC-Deformable-Registration-main\code\env.py", line 28, in __init__
self.reset()
File "E:\SPAC-Deformable-Registration-main\code\env.py", line 43, in reset
items = next(self.generator)
File "E:\SPAC-Deformable-Registration-main\code\data_util\brain.py", line 93, in generator
scheme = self.schemes[subset]
KeyError: 'lits'
