### ISSUE TITLE
TRAIN_SEG_DATA

### ISSUE THREAD

**Issue by zhouhanzhouhan** [Algolzw/SPAC-Deformable-Registration#5]
I want to reproduce this experiment，but i didn't know what is the relationship between the TRAIN_DATA and the TRAIN_SRG_DATA ,does the TRAIN_SRG_DATA means the label of the TRAIN_DATA? Would you mind share the TRAIN_SEG_DATA corresponding to  lits_val.h5?

**Comment by pds001** [comment]
Hello, I found an error in the operation process, hope to get your help, good luck!

Number of data in combine-train is 2302

Number of data in lpba-val is 39

Traceback (most recent call last):

File "E:\SPAC-Deformable-Registration-main\code\main.py", line 63, in <module>

env = Env(generator, stn, seg_stn, cfg.USE_SEG, device)

File "E:\SPAC-Deformable-Registration-main\code\env.py", line 28, in __init__

self.reset()

File "E:\SPAC-Deformable-Registration-main\code\env.py", line 43, in reset

items = next(self.generator)

File "E:\SPAC-Deformable-Registration-main\code\data_util\brain.py", line 93, in generator

scheme = self.schemes[subset]

KeyError: 'lits'
