### ISSUE TITLE
训练3d脑数据

### ISSUE THREAD

**Issue by degilala** [Algolzw/SPAC-Deformable-Registration#7]
您好，不好意思打扰了，请问我该怎么训练我自己的3d数据集，我的数据集是.nii格式。

**Comment by pds001** [comment]
Hello, I found an error in the operation process, hope to get your help, good luck!

Number of data in combine-train is 2302

Number of data in lpba-val is 39

Traceback (most recent call last):

File "E:\SPAC-Deformable-Registration-main\code\main.py", line 63, in <module>

env = Env(generator, stn, seg_stn, cfg.USE_SEG, device)

File "E:\SPAC-Deformable-Registration-main\code\env.py", line 28, in __init__

self.reset()

File "E:\SPAC-Deformable-Registration-main\code\env.py", line 43, in reset

items = next(self.generator)

File "E:\SPAC-Deformable-Registration-main\code\data_util\brain.py", line 93, in generator

scheme = self.schemes[subset]

KeyError: 'lits'
